routes/web.php
<?php
Route::redirect('/', '/admin/home');

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');

    /**SubAdmin Route */
    Route::get('/subadmin', 'Admin\SubAdminController@index')->name('sub_admin.index');
    Route::get('/subadmin/create', 'Admin\SubAdminController@create')->name('sub_admin.create');
    Route::post('/subadmin', 'Admin\SubAdminController@store')->name('sub_admin.store');
    Route::get('/subadmin/edit/{id}', 'Admin\SubAdminController@edit')->name('sub_admin.edit');
    Route::post('/subadmin/{id}', 'Admin\SubAdminController@update')->name('sub_admin.update');
    Route::get('/subadmin/delete/{id}', 'Admin\SubAdminController@delete')->name('sub_admin.delete');

    /**Country Route */
    Route::get('/country', 'Admin\CountryController@index')->name('country.index');
    Route::get('/country/create', 'Admin\CountryController@create')->name('country.create');
    Route::post('/country', 'Admin\CountryController@store')->name('country.store');
    Route::get('/country/edit/{id}', 'Admin\CountryController@edit')->name('country.edit');
    Route::post('/country/{id}', 'Admin\CountryController@update')->name('country.update');
    Route::get('/country/delete/{id}', 'Admin\CountryController@delete')->name('country.delete');

     /**Language Route */
     Route::get('/language', 'Admin\LanguageController@index')->name('language.index');
     Route::get('/language/create', 'Admin\LanguageController@create')->name('language.create');
     Route::post('/language', 'Admin\LanguageController@store')->name('language.store');
     Route::get('/language/edit/{id}', 'Admin\LanguageController@edit')->name('language.edit');
     Route::post('/language/{id}', 'Admin\LanguageController@update')->name('language.update');
     Route::get('/language/delete/{id}', 'Admin\LanguageController@delete')->name('language.delete');

     /**Package Route */
     Route::get('/package', 'Admin\PackageController@index')->name('package.index');
     Route::get('/package/create', 'Admin\PackageController@create')->name('package.create');
     Route::post('/package', 'Admin\PackageController@store')->name('package.store');
     Route::get('/package/edit/{id}', 'Admin\PackageController@edit')->name('package.edit');
     Route::post('/package/{id}', 'Admin\PackageController@update')->name('package.update');
     Route::get('/package/delete/{id}', 'Admin\PackageController@delete')->name('package.delete');

     /**Module Permission Route */
     Route::get('/module_permission', 'Admin\ModulePermissionController@index')->name('module_permission.index');
     Route::get('/module_permission/create', 'Admin\ModulePermissionController@create')->name('module_permission.create');
     Route::post('/module_permission', 'Admin\ModulePermissionController@store')->name('module_permission.store');
     Route::get('/module_permission/edit/{id}', 'Admin\ModulePermissionController@edit')->name('module_permission.edit');
     Route::post('/module_permission/{id}', 'Admin\ModulePermissionController@update')->name('module_permission.update');
     Route::get('/module_permission/delete/{id}', 'Admin\ModulePermissionController@delete')->name('module_permission.delete');

      /**Package Route */
      Route::get('/module_permission', 'Admin\ModulePermissionController@index')->name('module_permission.index');
      Route::get('/module_permission/create', 'Admin\ModulePermissionController@create')->name('module_permission.create');
      Route::post('/module_permission', 'Admin\ModulePermissionController@store')->name('module_permission.store');
      Route::get('/module_permission/edit/{id}', 'Admin\ModulePermissionController@edit')->name('module_permission.edit');
      Route::post('/module_permission/{id}', 'Admin\ModulePermissionController@update')->name('module_permission.update');
      Route::get('/module_permission/delete/{id}', 'Admin\ModulePermissionController@delete')->name('module_permission.delete');
});

app/Models/ModulePermission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ModulePermission extends Model
{
    public $timestamps = false;
    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/Admin/ModulePermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ModulePermission;

class ModulePermissionController extends Controller
{
    public function index(){
        $modulePermissions = ModulePermission::all();
        return view('admin.module-permission.index',compact('modulePermissions'));
    }

    public function create(){
        return view('admin.module-permission.create');
    }

    public function store(Request $request){
        $modulePermission = new ModulePermission;
        $modulePermission->name  = $request->name;
        $modulePermission->save();
        return redirect()->route('admin.module_permission.index')->withFlashSuccess('Module Permission is Saved');
    }

    public function edit($id){
        $modulePermission = ModulePermission::where('id',$id)->first();
        return view('admin.module-permission.edit',compact('modulePermission'));
    }

    public function update($id, Request $request){
        $modulePermission = ModulePermission::where('id',$id)->first();   
        $modulePermission->update($request->all());
        return redirect()->route('admin.module_permission.index')->withFlashSuccess('Module Permission is Updated');
    }

    public function delete($id){
        ModulePermission::where('id',$id)->delete();
        return redirect()->route('admin.module_permission.index')->withFlashSuccess('Module Permission is Deleted');
    }
}

resources/views/admin/module-permission/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="card">
    <div class="card-header">
        Add Module Permission
    </div>
    <div class="card-body">
        <form action="{{route('admin.module_permission.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="title">Name*</label>
                        <input type="text" id="name" name="name" class="form-control"  required>
                    </div>
                </div>
                <div  class="col-md-3">
                    <input class="btn btn-success" type="submit" value="Save">
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/module-permission/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="card">
    <div class="card-header">
        Add Module Permission
    </div>
    <div class="card-body">
        <form action="{{route('admin.module_permission.update',$modulePermission->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="title">Name*</label>
                        <input type="text" id="name" value="{{$modulePermission->name}}" name="name" class="form-control"  required>
                    </div>
                </div>
                <div  class="col-md-3">
                    <input class="btn btn-success" type="submit" value="Update">
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/module-permission/index.blade.php
@extends('layouts.admin')
@section('content')
<div style="margin-bottom: 10px;" class="row">
    <div class="col-lg-12">
        <a class="btn btn-success" href="{{ route("admin.module_permission.create") }}">
            Add Module Permissions
        </a>
    </div>
</div>
<div class="card">
    <div class="card-header">
        All Module Permissions
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th> Name</th>
                        <th> Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($modulePermissions as $modulePermission)
                    <tr>
                        <td>{{$modulePermission->name}}</td>
                        <td>
                            <a type='button' href="{{ route('admin.module_permission.edit',$modulePermission->id) }}" class="btn btn-sm btn-success"><i class="fa fa-edit"></i>&nbsp;&nbsp;Edit&nbsp;</a>&nbsp;&nbsp;
                            <a type='button' href="{{ route('admin.module_permission.delete',$modulePermission->id) }}" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i>&nbsp;&nbsp;Delete&nbsp;</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection