routes/web.php
<?php
Route::redirect('/', '/admin/home');

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('users.mass_destroy');

    /**SubAdmin Route */
    Route::get('/subadmin', 'Admin\SubAdminController@index')->name('sub_admin.index');
    Route::get('/subadmin/create', 'Admin\SubAdminController@create')->name('sub_admin.create');
    Route::post('/subadmin', 'Admin\SubAdminController@store')->name('sub_admin.store');
    Route::get('/subadmin/edit/{id}', 'Admin\SubAdminController@edit')->name('sub_admin.edit');
    Route::post('/subadmin/{id}', 'Admin\SubAdminController@update')->name('sub_admin.update');
    Route::get('/subadmin/delete/{id}', 'Admin\SubAdminController@delete')->name('sub_admin.delete');

    /**Country Route */
    Route::get('/country', 'Admin\CountryController@index')->name('country.index');
    Route::get('/country/create', 'Admin\CountryController@create')->name('country.create');
    Route::post('/country', 'Admin\CountryController@store')->name('country.store');
    Route::get('/country/edit/{id}', 'Admin\CountryController@edit')->name('country.edit');
    Route::post('/country/{id}', 'Admin\CountryController@update')->name('country.update');
    Route::get('/country/delete/{id}', 'Admin\CountryController@delete')->name('country.delete');

     /**Language Route */
     Route::get('/language', 'Admin\LanguageController@index')->name('language.index');
     Route::get('/language/create', 'Admin\LanguageController@create')->name('language.create');
     Route::post('/language', 'Admin\LanguageController@store')->name('language.store');
     Route::get('/language/edit/{id}', 'Admin\LanguageController@edit')->name('language.edit');
     Route::post('/language/{id}', 'Admin\LanguageController@update')->name('language.update');
     Route::get('/language/delete/{id}', 'Admin\LanguageController@delete')->name('language.delete');

     /**Package Route */
     Route::get('/package', 'Admin\PackageController@index')->name('package.index');
     Route::get('/package/create', 'Admin\PackageController@create')->name('package.create');
     Route::post('/package', 'Admin\PackageController@store')->name('package.store');
     Route::get('/package/edit/{id}', 'Admin\PackageController@edit')->name('package.edit');
     Route::post('/package/{id}', 'Admin\PackageController@update')->name('package.update');
     Route::get('/package/delete/{id}', 'Admin\PackageController@delete')->name('package.delete');

     /**Module Permission Route */
     Route::get('/module_permission', 'Admin\ModulePermissionController@index')->name('module_permission.index');
     Route::get('/module_permission/create', 'Admin\ModulePermissionController@create')->name('module_permission.create');
     Route::post('/module_permission', 'Admin\ModulePermissionController@store')->name('module_permission.store');
     Route::get('/module_permission/edit/{id}', 'Admin\ModulePermissionController@edit')->name('module_permission.edit');
     Route::post('/module_permission/{id}', 'Admin\ModulePermissionController@update')->name('module_permission.update');
     Route::get('/module_permission/delete/{id}', 'Admin\ModulePermissionController@delete')->name('module_permission.delete');

      /**Package Route */
      Route::get('/module_permission', 'Admin\ModulePermissionController@index')->name('module_permission.index');
      Route::get('/module_permission/create', 'Admin\ModulePermissionController@create')->name('module_permission.create');
      Route::post('/module_permission', 'Admin\ModulePermissionController@store')->name('module_permission.store');
      Route::get('/module_permission/edit/{id}', 'Admin\ModulePermissionController@edit')->name('module_permission.edit');
      Route::post('/module_permission/{id}', 'Admin\ModulePermissionController@update')->name('module_permission.update');
      Route::get('/module_permission/delete/{id}', 'Admin\ModulePermissionController@delete')->name('module_permission.delete');
});

app/Models/SubAdmin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\User;

class SubAdmin extends Model
{
    protected $fillable = [
        'user_id',
        'address',
        'phone',
        'country_id',
        'language_id'
    ];  

    public function users(){
        return $this->belongsTo(User::class,'user_id');
    }

    public function countries(){
        return $this->belongsTo(Country::class,'country_id');
    }

    public function languages(){
        return $this->belongsTo(Language::class,'language_id');
    }
}

app/Http/Controllers/Admin/SubAdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Country;
use App\Models\Language;
use App\User;
use App\Models\SubAdmin;
use Illuminate\Http\Request;

class SubAdminController extends Controller
{
    public function index(){
        $subadmins = SubAdmin::with('users','countries','languages')->get();
        return view('admin.sub-admin.index',compact('subadmins'));
    }

    public function create(){
        $countries = Country::all();
        $languages = Language::all();
        return view('admin.sub-admin.create',compact('countries','languages'));
    }

    public function store(Request $request){
        $user = new User;
        $user->name  = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt('password');
        $user->save();
        $subadmin = new SubAdmin;
        $subadmin->user_id        = $user->id;
        $subadmin->address        = $request->address;
        $subadmin->phone          = $request->phone;
        $subadmin->country_id     = $request->country_id;
        $subadmin->language_id     = $request->language_id;
        $subadmin->save();
        return redirect()->route('admin.sub_admin.index')->withFlashSuccess('Subadmin is Saved');
    }

    public function edit($id){
        $subadmin = SubAdmin::where('id',$id)->with('users','countries','languages')->first();
        $countries = Country::all();
        $languages = Language::all();
        return view('admin.sub-admin.edit',compact('subadmin','countries','languages'));
    }

    public function update($id, Request $request){
        $subadmin = Subadmin::where('id',$id)->first();   
        $user= User::where('id',$subadmin->user_id)->first();
        $user->update([
            'name'  => $request->name,
            'email' => $request->email
        ]);
        $subadmin->update([
            'address'    => $request->address,
            'phone'      => $request->phone,
            'country_id' => $request->country_id,
            'language_id'=> $request->language_id
        ]);
        return redirect()->route('admin.sub_admin.index')->withFlashSuccess('Subadmin is Updated');
    }

    public function delete($id){
        $subadmin = SubAdmin::where('id',$id)->first();
        User::where('id',$subadmin->user_id)->delete();
        $subadmin->delete();
        return redirect()->route('admin.sub_admin.index')->withFlashSuccess('Subadmin is Deleted');
    }
}

resources/views/admin/sub-admin/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="card">
    <div class="card-header">
        Create Sub Admin
    </div>

    <div class="card-body">
        <form action="{{route('admin.sub_admin.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Name*</label>
                        <input type="text" id="name" name="name" class="form-control"  required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Email*</label>
                        <input type="text" id="email" name="email" class="form-control"  required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Address*</label>
                        <input type="text" id="address" name="address" class="form-control"  required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Phone*</label>
                        <input type="text" id="phone" name="phone" class="form-control"  required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Country*</label>
                        <select class="form-control" name="country_id"  required >
                            <option  value="">Select Country</option>
                        @foreach($countries as $key=>$country)
                            <option   value="{{$country->id}}">{{$country->name}}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Language*</label>
                        <select class="form-control" name="language_id" required >
                            <option  value="">Select Language</option>
                        @foreach($languages as $key=>$language)
                            <option   value="{{$language->id}}">{{$language->name}}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
            </div>
            <div>
                <input class="btn btn-success" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/sub-admin/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="card">
    <div class="card-header">
        Create Sub Admin
    </div>

    <div class="card-body">
        <form action="{{route('admin.sub_admin.update',$subadmin->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Name*</label>
                        <input type="text" id="name" name="name" value="{{$subadmin->users->name}}" class="form-control"  required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Email*</label>
                        <input type="text" id="email" name="email" value="{{$subadmin->users->email}}"  class="form-control"  required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Address*</label>
                        <input type="text" id="address" name="address" value="{{$subadmin->address}}"  class="form-control"  required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Phone*</label>
                        <input type="text" id="phone" name="phone"  value="{{$subadmin->phone}}"  class="form-control"  required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Country*</label>
                        <select class="form-control" name="country_id"  required >
                            <option  value="">Select Country</option>
                        @foreach($countries as $key=>$country)
                            <option value="{{$country->id}}" {{$country->id == $subadmin->countries->id ? 'selected' : ''}} >{{$country->name}}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Language*</label>
                        <select class="form-control" name="language_id" required >
                            <option  value="">Select Language</option>
                        @foreach($languages as $key=>$language)
                            <option   value="{{$language->id}}"  {{$language->id == $subadmin->languages->id ? 'selected' : ''}}>{{$language->name}}</option>
                        @endforeach
                        </select>
                    </div>
                </div>
            </div>
            <div>
                <input class="btn btn-success" type="submit" value="Update">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/sub-admin/index.blade.php
@extends('layouts.admin')
@section('content')
@can('users_manage')
<div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.sub_admin.create") }}">
                Add Sub Admin
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        All Sub Admins
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>                                                    
                        <th>Country</th>
                        <th>Address</th>
                        <th>Phone</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($subadmins as $subadmin)
                    <tr>
                        <td>{{$subadmin->users->name}}</td>
                        <td>{{$subadmin->users->email}}</td>
                        <td>{{$subadmin->countries->name}}</td>
                        <td>{{$subadmin->languages->name}}</td>
                        <td>{{$subadmin->phone}}</td>
                        <td>
                            <a type='button' href="{{ route('admin.sub_admin.edit',$subadmin->id) }}" class="btn btn-sm btn-success"><i class="fa fa-edit"></i>&nbsp;&nbsp;Edit&nbsp;</a>&nbsp;&nbsp;
                            <a type='button' href="{{ route('admin.sub_admin.delete',$subadmin->id) }}" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i>&nbsp;&nbsp;Delete&nbsp;</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection